services:
  backend:
    build: ./backend
    image: my-backend:latest
    container_name: backend
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./openvpn-data/conf:/etc/openvpn

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    restart: always
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    cap_add:
      - NET_ADMIN
